blank_issues_enabled: false
contact_links:
  - name: freee API へのご要望 / freee API feature request
    url: https://docs.google.com/forms/d/e/1FAIpQLSdG19OrIdc0nbI-F5L1hkYRAfh4l-qD0ugvuFqxvaOUdXVqXg/viewform
    about: freee API 自体の機能追加・改善のご要望はこちらのフォームからお送りください。
