/**
 * Generates `src/mcp/vibes-css.ts` from the published freee Vibes stylesheet.
 *
 * The MCP Apps upload view (src/mcp/file-upload-app-html.ts) is a single
 * self-contained HTML document: the host CSP forbids external stylesheets, and
 * @freee_jp/vibes itself is a React component library this plain-HTML app
 * cannot use. So the real Vibes rules for the classes the view uses are
 * extracted here and inlined, instead of hand-copying token values.
 *
 * Not a build-time dependency on purpose: the package pulls React,
 * styled-components and friends as peers, which is a lot of install for one
 * stylesheet. The tarball is fetched on demand and the result is committed.
 *
 *   bun run generate:vibes-css
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const VIBES_VERSION = '100.1.0';
const CSS_PATH_IN_TARBALL = 'package/vibes_2021.min.css';
const OUT_FILE = join(import.meta.dir, '..', 'src', 'mcp', 'vibes-css.ts');

/** Classes used by the upload view. A rule is kept when its selector mentions one. */
const USED_CLASSES = [
  'vb-sectionTitle',
  'vb-note',
  'vb-fileUploader',
  'vb-button',
  'vb-textField',
  'vb-select__body',
  'vb-formControlLabel__text',
  'vb-inlineLink',
];

async function fetchStylesheet(): Promise<string> {
  const url = `https://registry.npmjs.org/@freee_jp/vibes/-/vibes-${VIBES_VERSION}.tgz`;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`download failed: ${response.status} ${url}`);
  const tarball = Buffer.from(await response.arrayBuffer());
  const tar = Bun.spawn(['tar', '-xzO', CSS_PATH_IN_TARBALL], {
    stdin: tarball,
    stdout: 'pipe',
    stderr: 'pipe',
  });
  const css = await new Response(tar.stdout).text();
  if ((await tar.exited) !== 0 || css.length === 0) {
    throw new Error(`could not extract ${CSS_PATH_IN_TARBALL}: ${await new Response(tar.stderr).text()}`);
  }
  return css;
}

interface Block {
  prelude: string;
  body: string;
}

/** Splits one nesting level into `selector { body }` blocks. */
function splitBlocks(css: string): Block[] {
  const blocks: Block[] = [];
  let start = 0;
  let depth = 0;
  let preludeEnd = -1;
  for (let i = 0; i < css.length; i++) {
    const ch = css[i];
    if (ch === '{') {
      if (depth === 0) preludeEnd = i;
      depth++;
    } else if (ch === '}') {
      depth--;
      if (depth === 0) {
        blocks.push({
          prelude: css.slice(start, preludeEnd).trim(),
          body: css.slice(preludeEnd + 1, i),
        });
        start = i + 1;
      }
    }
  }
  return blocks;
}

const isUsed = (selector: string): boolean => USED_CLASSES.some((cls) => selector.includes(cls));
// External assets (fonts, images) cannot load under the app's CSP.
const hasExternalAsset = (body: string): boolean => /url\((?!['"]?data:)/.test(body);

function extract(css: string): string {
  const kept: string[] = [];
  for (const block of splitBlocks(css)) {
    if (block.prelude.startsWith('@font-face') || block.prelude.startsWith('@keyframes')) continue;
    if (block.prelude.startsWith('@media') || block.prelude.startsWith('@supports')) {
      const inner = splitBlocks(block.body)
        .filter((r) => isUsed(r.prelude) && !hasExternalAsset(r.body))
        .map((r) => `${r.prelude}{${r.body}}`)
        .join('');
      if (inner) kept.push(`${block.prelude}{${inner}}`);
      continue;
    }
    if (isUsed(block.prelude) && !hasExternalAsset(block.body)) {
      kept.push(`${block.prelude}{${block.body}}`);
    }
  }
  return kept.join('\n');
}

const css = extract(await fetchStylesheet());
if (!css.includes('.vb-button')) throw new Error('extraction produced no button rules; check USED_CLASSES');

writeFileSync(
  OUT_FILE,
  `// Generated by scripts/generate-vibes-css.ts from @freee_jp/vibes@${VIBES_VERSION}. Do not edit.\n` +
    `export const VIBES_CSS = ${JSON.stringify(css)};\n`,
);
// Biome owns the quoting and wrapping of the emitted literal, so `bun run check`
// stays green right after a regeneration.
await Bun.spawn(['bunx', 'biome', 'format', '--write', OUT_FILE], { stdout: 'ignore' }).exited;
console.log(`wrote ${OUT_FILE} (${css.length} bytes of CSS)`);
